#!/bin/bash

function usage () {
	if [ -n "$1" ] ; then
		echo $1 >&2
	else
		echo "Start as docker run -h \$FQDN_HOSTNAME -e PASSWORD=\$THE_ADMIN_PASSWORD image" >&2
	fi
	exit 1
}

function stop_running () {
	systemctl stop-running
}
trap stop_running TERM

systemctl stop dbus.service
rm -f /var/run/messagebus.pid
rm -f /etc/systemctl-lite/running/*

systemctl start sshd.service

if [ -f /etc/ipa/ca.crt ] ; then
	echo "FreeIPA server is already configured, starting the services."
	systemctl start-enabled
	echo "FreeIPA server started."
else
	HOSTNAME_FQDN=$( hostname -f )
	HOSTNAME_SHORT=${HOSTNAME_FQDN%%.*}
	DOMAIN=${HOSTNAME_FQDN#*.}
	if [ "$HOSTNAME_SHORT.$DOMAIN" != "$HOSTNAME_FQDN" ] ; then
		usage
	fi

	if [ -z "$PASSWORD" ] ; then
		usage
	fi

	REALM=${DOMAIN^^}

	DEBUG_OPT=
	if [ -n "$DEBUG" ] ; then
		DEBUG_OPT=-d
	fi

	/usr/sbin/ipa-server-install -r $REALM -p $PASSWORD -P $PASSWORD -a $PASSWORD -U $DEBUG_OPT < /dev/null
	echo "FreeIPA server configured."
fi

if perl -e '( -t ) ? exit 0 : exit 1' ; then
	echo 'Starting interactive shell.'
	/bin/bash
else
	echo 'Go loop.'
	while true ; do sleep 1000 ; done
fi

