#!/bin/bash

set -e

j=1
for i in 389-ds-base dogtag-pki-base bind-dyndb-ldap certmonger ; do
	rpm -q $i || continue
	s=/usr/sbin/ipa-upgrade-rpm-scriptlets-$j-$i
	rpm -q --qf '#!%{POSTINPROG}\n%{POSTIN}\n' $i | sed 's%#!/bin/sh%#!/bin/sh -x%' > $s
	sed -i '\|/sbin/ldconfig|d;s%/etc/named.conf%/data/etc/named.conf%' $s
	chmod -v a+x $s
	j=$(( j + 1 ))
done

rm -f /var/lib/rpm/__db.*
