name: Install and start K0s
runs:
  using: composite
  steps:
    - run: |
        curl -sSLf https://get.k0s.sh | sudo sh
        sudo mkdir /etc/k0s
        sudo cp tests/k0s-service-subnet.yaml /etc/k0s/k0s.yaml

        if [ -e /var/run/crio/crio.sock ] ; then
            CRI_SOCKET='--cri-socket remote:unix:///var/run/crio/crio.sock'
        elif [ -e /var/run/containerd/containerd.sock ] ; then
            CRI_SOCKET='--cri-socket remote:unix:///var/run/containerd/containerd.sock'
        fi
        sudo k0s install controller --single $CRI_SOCKET -c /etc/k0s/k0s.yaml
        sudo k0s start
        ( set +x ; while ! sudo k0s status ; do echo --- ; sleep 5 ; done )

        ( echo '#!/bin/bash' ; echo 'KUBECONFIG=~/.kube/config exec k0s kubectl "$@"' ) | sudo tee /usr/local/bin/kubectl
        sudo chmod a+x /usr/local/bin/kubectl

        mkdir ~/.kube
        sudo cat /var/lib/k0s/pki/admin.conf > ~/.kube/config

        ( set +x ; while true ; do if kubectl get nodes | tee /dev/stderr | grep -q '\bReady\b' ; then break ; else sleep 5 ; fi ; done )
        ( set +x ; while ! kubectl get serviceaccount/default ; do sleep 5 ; done )
        kubectl get pods --all-namespaces
        ( set +x ; while kubectl get pods -A 2>&1 | grep -E 'Pending|ContainerCreating|Init|No resources found' ; do echo --- ; sleep 5 ; done )
        kubectl get pods --all-namespaces

        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
        # Remove the extremely permissive ACLs / mask that GitHub runners have on /opt
        # which prevents sssd.service from starting due to
        # [sssd] [access_check_file] (0x0020): Unexpected access to '/etc/sssd/sssd.conf' by other users
        sudo mkdir /opt/local-path-provisioner
        sudo setfacl -b /opt/local-path-provisioner

        ( set +x ; for i in $( seq 1 10 ) ; do ip link show cni0 > /dev/null && break ; sleep 3 ; done )
        sudo resolvectl dns cni0 $( kubectl get -n kube-system service/kube-dns -o 'jsonpath={.spec.clusterIP}' )
        sudo resolvectl domain cni0 cluster.local

        kubectl apply -f tests/freeipa-coredns-custom.yaml
        if ! kubectl get configmap -n kube-system coredns -o yaml | grep -F 'import /etc/coredns/custom/*.server' ; then
            ( kubectl get configmap -n kube-system coredns -o=jsonpath='{.data.Corefile}' ;
                kubectl get configmap -n kube-system coredns-custom -o=jsonpath="{.data['freeipa\.server']}" ) \
            | kubectl create --dry-run=client -n kube-system configmap coredns --from-file=Corefile=/dev/stdin -o yaml \
            | kubectl apply -n kube-system -f -
        fi
        ( set +x ; for i in $( seq 1 30 ) ; do dig +short kubernetes.default.svc.cluster.local && break ; sleep 3 ; done )
      shell: bash -euxo pipefail {0}
